### PR TITLE
New feature and merging with master

### PR DESCRIPTION
**Pull request by VanDerSam**

### CODE REVIEW

**Comment by ghost** [comment]
Hi. I'll take a look at the code, but please do a **git pull** in your repo before doing a _pull request_ - your code undoes some of my changes that I've just made last week. BR.

**Comment by ghost** [comment]
I have rebased and changed your pull request. Please clean your repo (maybe drop your current fork and do a new one?) before doing other changes. BR.

**Comment by VanDerSam** [comment]
Hi. I made "git pull" before I started my last changed. When I finished my changes I detect than there were 8 new commits in original repository. I made "git pull" command again. There was 1 conflict in About dialog. It was little difference. I fixed it and made new commit. After that I created the pull request.
Can you explain to me what I need to do in these situations?

**Comment by ghost** [comment]
In my opinion, the best solution is to do a _git rebase_ after a _git pull_. That's what I have done to handle your pull request.

There was a conflict, but it was easy to fix. After that, I've done some code cleanup and refactoring, too :-)

This post might help: https://differential.com/insights/best-way-to-merge-a-github-pull-request/

**Comment by VanDerSam** [comment]
Thanks for the advice. I will read and practice:)

**Pull request closed without merging**
